// TypeScript port of cc_history.py's JSONL parsing + truncation, kept BYTE-EXACT
// with the Python CLI so both tools can share one index.db. The golden contract
// in shared/fixtures/expected-entries.json (generated by the CLI) is the
// authority; src/test asserts this port reproduces it exactly.
//
// Ground truth: ../../cc-history/cc_history.py — parse_line, parse_blocks,
// _stringify, _truncate. Mirror their rules precisely:
//   - empty/whitespace text & thinking blocks are DROPPED
//   - tool_result with empty/whitespace content is DROPPED; tool_use is NOT
//   - bare string blocks inside content become `text` entries
//   - tool_use text = `${name}(${pyJson(input)})`, truncated to 4096 bytes
//   - tool_result text = stringify(content), truncated to 8192 bytes
//   - truncation is on UTF-8 BYTES, dropping a partial trailing code point
//     (Python's raw[:limit].decode("utf-8", errors="ignore")), then appending
//     `\n[…truncated, full length N bytes]`.

export const TOOL_USE_MAX = 4096;
export const TOOL_RESULT_MAX = 8192;

export type Kind = "text" | "thinking" | "tool_use" | "tool_result";
export type Role = "user" | "assistant";

export interface ParsedEntry {
  role: Role;
  kind: Kind;
  tool_name: string | null;
  text: string;
}

/**
 * Serialize a value the way Python's `json.dumps(v, ensure_ascii=False)` does:
 * item separator ", " and key separator ": " (note the spaces), non-ASCII kept
 * literally, object key order preserved. JSON.stringify handles scalar/string
 * escaping identically; only containers need the Python separators.
 */
export function pyJson(v: unknown): string {
  if (v === null || v === undefined) {
    return "null";
  }
  const t = typeof v;
  if (t === "string" || t === "number" || t === "boolean") {
    return JSON.stringify(v);
  }
  if (Array.isArray(v)) {
    return "[" + v.map(pyJson).join(", ") + "]";
  }
  if (t === "object") {
    const parts = Object.entries(v as Record<string, unknown>).map(
      ([k, val]) => JSON.stringify(k) + ": " + pyJson(val)
    );
    return "{" + parts.join(", ") + "}";
  }
  return JSON.stringify(v);
}

/** Mirror cc_history._stringify: strings pass through raw; everything else pyJson. */
export function stringifyContent(content: unknown): string {
  if (typeof content === "string") {
    return content;
  }
  return pyJson(content);
}

/**
 * Byte-exact port of cc_history._truncate. Truncates `text` to `limitBytes` of
 * UTF-8, dropping any partial trailing code point (never emitting U+FFFD), then
 * appends the truncation marker with the FULL original byte length.
 */
export function truncate(text: string, limitBytes: number): string {
  const buf = Buffer.from(text, "utf8");
  if (buf.length <= limitBytes) {
    return text;
  }
  // Find the largest prefix of buf[0:limit] that ends on a complete code point.
  let end = limitBytes;
  // Walk back from the boundary to the last lead byte within the slice.
  let k = end - 1;
  while (k >= 0 && (buf[k] & 0xc0) === 0x80) {
    k--; // skip continuation bytes (10xxxxxx)
  }
  if (k >= 0) {
    const lead = buf[k];
    let seqLen = 1;
    if ((lead & 0x80) === 0x00) {
      seqLen = 1;
    } else if ((lead & 0xe0) === 0xc0) {
      seqLen = 2;
    } else if ((lead & 0xf0) === 0xe0) {
      seqLen = 3;
    } else if ((lead & 0xf8) === 0xf0) {
      seqLen = 4;
    }
    const avail = end - k;
    if (avail < seqLen) {
      // The sequence starting at k is cut off by the byte limit — drop it.
      end = k;
    }
  }
  const clipped = buf.subarray(0, end).toString("utf8");
  return `${clipped}\n[…truncated, full length ${buf.length} bytes]`;
}

function isNonEmpty(s: unknown): s is string {
  return typeof s === "string" && s.trim().length > 0;
}

/** Port of cc_history.parse_blocks. */
export function parseBlocks(role: Role, content: unknown): ParsedEntry[] {
  const out: ParsedEntry[] = [];
  if (typeof content === "string") {
    if (content.trim().length > 0) {
      out.push({ role, kind: "text", tool_name: null, text: content });
    }
    return out;
  }
  if (!Array.isArray(content)) {
    return out;
  }
  for (const block of content) {
    if (typeof block !== "object" || block === null) {
      if (isNonEmpty(block)) {
        out.push({ role, kind: "text", tool_name: null, text: block });
      }
      continue;
    }
    const b = block as Record<string, unknown>;
    switch (b.type) {
      case "text": {
        const txt = (b.text as string) ?? "";
        if (txt.trim().length > 0) {
          out.push({ role, kind: "text", tool_name: null, text: txt });
        }
        break;
      }
      case "thinking": {
        const txt = (b.thinking as string) ?? "";
        if (txt.trim().length > 0) {
          out.push({ role: "assistant", kind: "thinking", tool_name: null, text: txt });
        }
        break;
      }
      case "tool_use": {
        const name = (b.name as string) ?? "";
        const text = truncate(`${name}(${pyJson(b.input)})`, TOOL_USE_MAX);
        out.push({ role: "assistant", kind: "tool_use", tool_name: name, text });
        break;
      }
      case "tool_result": {
        const text = truncate(stringifyContent(b.content), TOOL_RESULT_MAX);
        if (text.trim().length > 0) {
          out.push({ role: "user", kind: "tool_result", tool_name: null, text });
        }
        break;
      }
      default:
        // image / anything else: skip
        break;
    }
  }
  return out;
}

export interface ParsedLine {
  ts: string | null;
  entries: ParsedEntry[];
}

/** Port of cc_history.parse_line. */
export function parseLine(obj: Record<string, unknown>): ParsedLine {
  const otype = obj.type;
  if (otype !== "user" && otype !== "assistant") {
    return { ts: null, entries: [] }; // queue-operation, summary, etc.
  }
  const role = otype as Role;
  const ts = (obj.timestamp as string) ?? null;
  let message = obj.message;

  if (typeof message === "string") {
    const raw = message;
    try {
      message = JSON.parse(raw);
    } catch {
      return { ts, entries: [{ role, kind: "text", tool_name: null, text: raw }] };
    }
  }

  if (typeof message === "object" && message !== null) {
    const content = (message as Record<string, unknown>).content;
    return { ts, entries: parseBlocks(role, content) };
  }
  return { ts, entries: [] };
}
